In [1]:
import warnings
warnings.filterwarnings("ignore")

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.utils import resample
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_validate, KFold

from sklearn.metrics import recall_score, roc_auc_score, f1_score
from sklearn.metrics import accuracy_score, roc_auc_score, \
                            classification_report, confusion_matrix

In [3]:
from sklearn.linear_model import LogisticRegression

In [4]:
#Read Data which was cleaned and pre-processed data.
df_selected = pd.read_csv('./dataset/Cleaned_data.csv')

In [5]:
df_selected.describe(include = 'all')

Unnamed: 0     loan_amnt          term      int_rate   installment  \
count  1.345310e+06  1.345310e+06  1.345310e+06  1.345310e+06  1.345310e+06   
mean   1.078824e+06  1.441997e+04  2.412581e-01  1.323962e+01  4.380755e+02   
std    6.841849e+05  8.717051e+03  4.278467e-01  4.768716e+00  2.615126e+02   
min    0.000000e+00  5.000000e+02  0.000000e+00  5.310000e+00  4.930000e+00   
25%    3.783052e+05  8.000000e+03  0.000000e+00  9.750000e+00  2.484800e+02   
50%    1.118210e+06  1.200000e+04  0.000000e+00  1.274000e+01  3.754300e+02   
75%    1.755354e+06  2.000000e+04  0.000000e+00  1.599000e+01  5.807300e+02   
max    2.260697e+06  4.000000e+04  1.000000e+00  3.099000e+01  1.719830e+03   

              grade     sub_grade    emp_length  home_ownership    annual_inc  \
count  1.345310e+06  1.345310e+06  1.345310e+06    1.345310e+06  1.345310e+06   
mean   1.745809e+00  1.069302e+01  6.052432e+00    2.911998e+00  7.624764e+04   
std    1.295071e+00  6.449912e+00  3.562249e+00    1.915676e+00  6.992510e+04   
min    0.000000e+00  0.000000e+00  1.000000e+00    0.000000e+00  0.000000e+00   
25%    1.000000e+00  6.000000e+00  2.000000e+00    1.000000e+00  4.578000e+04   
50%    2.000000e+00  1.000000e+01  6.000000e+00    4.000000e+00  6.500000e+04   
75%    2.000000e+00  1.400000e+01  1.000000e+01    5.000000e+00  9.000000e+04   
max    6.000000e+00  3.400000e+01  1.000000e+01    5.000000e+00  1.099920e+07   

       ...  fico_range_high      open_acc       pub_rec     revol_bal  \
count  ...     1.345310e+06  1.345310e+06  1.345310e+06  1.345310e+06   
mean   ...     7.001852e+02  1.159352e+01  2.152760e-01  1.624811e+04   
std    ...     3.185316e+01  5.473789e+00  6.018647e-01  2.232817e+04   
min    ...     6.290000e+02  0.000000e+00  0.000000e+00  0.000000e+00   
25%    ...     6.740000e+02  8.000000e+00  0.000000e+00  5.943000e+03   
50%    ...     6.940000e+02  1.100000e+01  0.000000e+00  1.113400e+04   
75%    ...     7.140000e+02  1.400000e+01  0.000000e+00  1.975575e+04   
max    ...     8.500000e+02  9.000000e+01  8.600000e+01  2.904836e+06   

         revol_util     total_acc  initial_list_status  application_type  \
count  1.345310e+06  1.345310e+06         1.345310e+06      1.345310e+06   
mean   5.181002e+01  2.498084e+01         5.827727e-01      1.917774e-02   
std    2.451326e+01  1.199847e+01         4.931013e-01      1.371494e-01   
min    0.000000e+00  2.000000e+00         0.000000e+00      0.000000e+00   
25%    3.350000e+01  1.600000e+01         0.000000e+00      0.000000e+00   
50%    5.210000e+01  2.300000e+01         1.000000e+00      0.000000e+00   
75%    7.070000e+01  3.200000e+01         1.000000e+00      0.000000e+00   
max    8.923000e+02  1.760000e+02         1.000000e+00      1.000000e+00   

       disbursement_method   issue_month  
count         1.345310e+06  1.345310e+06  
mean          5.128929e-03  5.531292e+00  
std           7.143268e-02  3.412514e+00  
min           0.000000e+00  0.000000e+00  
25%           0.000000e+00  3.000000e+00  
50%           0.000000e+00  5.000000e+00  
75%           0.000000e+00  9.000000e+00  
max           1.000000e+00  1.100000e+01  

[8 rows x 25 columns]

In [10]:
df_selected=df_selected.drop(df_selected.columns[0], axis=1)

In [11]:
df_selected.describe(include = 'all')

loan_amnt          term      int_rate   installment         grade  \
count  1.345310e+06  1.345310e+06  1.345310e+06  1.345310e+06  1.345310e+06   
mean   1.441997e+04  2.412581e-01  1.323962e+01  4.380755e+02  1.745809e+00   
std    8.717051e+03  4.278467e-01  4.768716e+00  2.615126e+02  1.295071e+00   
min    5.000000e+02  0.000000e+00  5.310000e+00  4.930000e+00  0.000000e+00   
25%    8.000000e+03  0.000000e+00  9.750000e+00  2.484800e+02  1.000000e+00   
50%    1.200000e+04  0.000000e+00  1.274000e+01  3.754300e+02  2.000000e+00   
75%    2.000000e+04  0.000000e+00  1.599000e+01  5.807300e+02  2.000000e+00   
max    4.000000e+04  1.000000e+00  3.099000e+01  1.719830e+03  6.000000e+00   

          sub_grade    emp_length  home_ownership    annual_inc  \
count  1.345310e+06  1.345310e+06    1.345310e+06  1.345310e+06   
mean   1.069302e+01  6.052432e+00    2.911998e+00  7.624764e+04   
std    6.449912e+00  3.562249e+00    1.915676e+00  6.992510e+04   
min    0.000000e+00  1.000000e+00    0.000000e+00  0.000000e+00   
25%    6.000000e+00  2.000000e+00    1.000000e+00  4.578000e+04   
50%    1.000000e+01  6.000000e+00    4.000000e+00  6.500000e+04   
75%    1.400000e+01  1.000000e+01    5.000000e+00  9.000000e+04   
max    3.400000e+01  1.000000e+01    5.000000e+00  1.099920e+07   

       verification_status  ...  fico_range_high      open_acc       pub_rec  \
count         1.345310e+06  ...     1.345310e+06  1.345310e+06  1.345310e+06   
mean          3.015669e-01  ...     7.001852e+02  1.159352e+01  2.152760e-01   
std           4.589384e-01  ...     3.185316e+01  5.473789e+00  6.018647e-01   
min           0.000000e+00  ...     6.290000e+02  0.000000e+00  0.000000e+00   
25%           0.000000e+00  ...     6.740000e+02  8.000000e+00  0.000000e+00   
50%           0.000000e+00  ...     6.940000e+02  1.100000e+01  0.000000e+00   
75%           1.000000e+00  ...     7.140000e+02  1.400000e+01  0.000000e+00   
max           1.000000e+00  ...     8.500000e+02  9.000000e+01  8.600000e+01   

          revol_bal    revol_util     total_acc  initial_list_status  \
count  1.345310e+06  1.345310e+06  1.345310e+06         1.345310e+06   
mean   1.624811e+04  5.181002e+01  2.498084e+01         5.827727e-01   
std    2.232817e+04  2.451326e+01  1.199847e+01         4.931013e-01   
min    0.000000e+00  0.000000e+00  2.000000e+00         0.000000e+00   
25%    5.943000e+03  3.350000e+01  1.600000e+01         0.000000e+00   
50%    1.113400e+04  5.210000e+01  2.300000e+01         1.000000e+00   
75%    1.975575e+04  7.070000e+01  3.200000e+01         1.000000e+00   
max    2.904836e+06  8.923000e+02  1.760000e+02         1.000000e+00   

       application_type  disbursement_method   issue_month  
count      1.345310e+06         1.345310e+06  1.345310e+06  
mean       1.917774e-02         5.128929e-03  5.531292e+00  
std        1.371494e-01         7.143268e-02  3.412514e+00  
min        0.000000e+00         0.000000e+00  0.000000e+00  
25%        0.000000e+00         0.000000e+00  3.000000e+00  
50%        0.000000e+00         0.000000e+00  5.000000e+00  
75%        0.000000e+00         0.000000e+00  9.000000e+00  
max        1.000000e+00         1.000000e+00  1.100000e+01  

[8 rows x 24 columns]

In [12]:
#Class Balance is checked and we see that both classes are unbalanced
#To solve the problem of unbalanced class and here we solve it using upsampling minority.It improves the model's generalization
# on unseen data
df_selected.loan_status.value_counts(normalize=True)

1    0.800374
0    0.199626
Name: loan_status, dtype: float64

In [13]:
df_selected.loan_status.value_counts()

1    1076751
0     268559
Name: loan_status, dtype: int64

In [21]:
#One of the popular techniques for dealing with highly unbalanced data sets is called resampling. 
#Although the technique has proven to be effective in many cases to solve the unbalanced class issue, however, 
#these techniques also have their weaknesses. For example, over-sampling records from the minority class, which can lead 
#to overfitting while removing random records from the majority class, which can cause loss of information.

df_major = df_selected[df_selected.loan_status == 1]
df_minor = df_selected[df_selected.loan_status == 0]

In [22]:
df_minor_upsmapled = resample(df_minor, replace = True, n_samples = 1076751, random_state = 2018)

In [23]:
df_minor_upsmapled = pd.concat([df_minor_upsmapled, df_major])

In [24]:
df_minor_upsmapled.loan_status.value_counts()

1    1076751
0    1076751
Name: loan_status, dtype: int64

In [25]:
#To see the performance of the unknown data, we use a function named as "evaluate_model" which prints 
#different evaluation criteria: 1) accuracy, 2) ROC-AUC score, 3) confusion matrix and 4) detailed classification report.

def evaluate_model(ytest, ypred, ypred_proba = None):
    if ypred_proba is not None:
        print('ROC-AUC score of the model: {}'.format(roc_auc_score(ytest, ypred_proba[:, 1])))
    print('Accuracy of the model: {}\n'.format(accuracy_score(ytest, ypred)))
    print('Classification report: \n{}\n'.format(classification_report(ytest, ypred)))
    print('Confusion matrix: \n{}\n'.format(confusion_matrix(ytest, ypred)))

In [26]:
#Standardize the data.
X = df_minor_upsmapled.drop('loan_status', axis = 1)
Y = df_minor_upsmapled.loan_status

In [27]:
xtrain, xtest, ytrain, ytest = train_test_split(X, Y, test_size=0.25, random_state=0)

In [28]:
mms = StandardScaler()
mms.fit(xtrain)
xtrain_scaled = mms.transform(xtrain)

In [29]:
np.shape(df_minor_upsmapled)

(2153502, 24)

In [30]:
#Logistic Regression Model
logisticRegr = LogisticRegression()

In [32]:
logisticRegr.fit(xtrain_scaled, ytrain)

LogisticRegression()

In [33]:
xtest_scaled = mms.transform(xtest)

In [34]:
lr_pred = logisticRegr.predict(xtest_scaled)

In [36]:
evaluate_model(ytest, lr_pred)

Accuracy of the model: 0.6495348975437241

Classification report: 
              precision    recall  f1-score   support

           0       0.65      0.64      0.64    269305
           1       0.65      0.66      0.65    269071

    accuracy                           0.65    538376
   macro avg       0.65      0.65      0.65    538376
weighted avg       0.65      0.65      0.65    538376


Confusion matrix: 
[[171262  98043]
 [ 90639 178432]]



In [37]:
#Random Forest Model: We use this model here because we have a lot of categorical variables which work best with
# decision trees. So, this model may give better accuracy than Logistic Regression.

def random_forest(xtrain, xtest, ytrain):
    rf_params = {
        'n_estimators': 126, 
        'max_depth': 14
    }

    rf = RandomForestClassifier(**rf_params)
    rf.fit(xtrain, ytrain)
    rfpred = rf.predict(xtest)
    rfpred_proba = rf.predict_proba(xtest)
    
    return rfpred, rfpred_proba

In [38]:
rfpred, rfpred_proba = random_forest(xtrain_scaled, xtest_scaled, ytrain)

In [39]:
evaluate_model(ytest, rfpred, rfpred_proba)

#Here, we see that there is almost 10% increase in accuracy in the RF model compared to LR model.

ROC-AUC score of the model: 0.755971549095154
Accuracy of the model: 0.6877869741593235

Classification report: 
              precision    recall  f1-score   support

           0       0.68      0.72      0.70    269305
           1       0.70      0.65      0.68    269071

    accuracy                           0.69    538376
   macro avg       0.69      0.69      0.69    538376
weighted avg       0.69      0.69      0.69    538376


Confusion matrix: 
[[194675  74630]
 [ 93458 175613]]



In [41]:
#To improve the model genralization on testing data, we try gradient-boosted tree based alogorithm.
# Here , we use LightGBM model to determine accuracy.

import lightgbm

In [42]:
lbg_params = {
    'n_estimators': 8000,
    'max_depth': 100,
    'objective': 'binary',
    'learning_rate' : 0.02,
    'num_leaves' : 250,
    'feature_fraction': 0.64, 
    'bagging_fraction': 0.8, 
    'bagging_freq': 1,
    'boosting_type' : 'gbdt'
}

In [43]:
lgb = lightgbm.LGBMClassifier(**lbg_params)

In [44]:
lgb.fit(xtrain_scaled, ytrain)

[LightGBM] [Warning] feature_fraction is set=0.64, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.64
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=1, subsample_freq=0 will be ignored. Current value: bagging_freq=1


LGBMClassifier(bagging_fraction=0.8, bagging_freq=1, feature_fraction=0.64,
               learning_rate=0.02, max_depth=100, n_estimators=8000,
               num_leaves=250, objective='binary')

In [45]:
lgb_pred = lgb.predict(xtest_scaled)

In [46]:
lgb_pred_proba = lgb.predict_proba(xtest_scaled)

In [47]:
evaluate_model(ytest, lgb_pred, lgb_pred_proba)

ROC-AUC score of the model: 0.889605784002013
Accuracy of the model: 0.8085130094952226

Classification report: 
              precision    recall  f1-score   support

           0       0.78      0.86      0.82    269305
           1       0.84      0.76      0.80    269071

    accuracy                           0.81    538376
   macro avg       0.81      0.81      0.81    538376
weighted avg       0.81      0.81      0.81    538376


Confusion matrix: 
[[230658  38647]
 [ 64445 204626]]



In [ ]:
#As we can see that the accuracy is now almost 89% which increased by 24% when compared to LR model and an increase of
# 14% compared to RF model.